import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('./useCloudAccount.ts', import.meta.url), 'utf8');

assert.match(source, /onAuthStateChange/);
assert.match(source, /PASSWORD_RECOVERY/);
assert.match(source, /signUp\(/);
assert.match(source, /createSupabasePlayerProfileDataSource/);
assert.match(source, /validateUsername/);
assert.match(source, /normalizeUsername/);
assert.match(source, /profileDataSource\.isUsernameAvailable\(normalizedUsername\)/);
assert.match(source, /data:\s*\{\s*username:\s*normalizedUsername\s*\}/);
assert.match(source, /profileDataSource\.fetch\(userId\)/);
assert.match(source, /setProfile\(null\)/);
assert.match(source, /profileStatus/);
assert.match(source, /profileError/);
assert.match(source, /profileMutationStatus/);
assert.match(source, /profileMutationMessage/);
assert.match(source, /profileMutationError/);
assert.match(source, /const changeUsername = useCallback\(async \(username: string\)/);
assert.match(source, /getUsernameChangeRemainingMs\(profile\)/);
assert.match(source, /normalizedUsername\.toLowerCase\(\) === profile\.username\.toLowerCase\(\)/);
assert.match(source, /profileDataSource\.isUsernameAvailable\(normalizedUsername\)/);
assert.match(source, /profileDataSource\.changeUsername\(normalizedUsername\)/);
assert.match(source, /setProfile\(updatedProfile\)/);
assert.match(source, /signInWithPassword/);
assert.match(source, /resetPasswordForEmail/);
assert.match(source, /updateUser\(\{\s*password/);
assert.match(source, /AUTOSAVE_DELAY_MS\s*=\s*3000/);
assert.match(source, /SAFETY_SYNC_INTERVAL_MS\s*=\s*30000/);
assert.match(source, /addEventListener\(['"]online['"]/);
assert.match(source, /removeEventListener\(['"]online['"]/);
assert.match(source, /clearTimeout/);
assert.match(source, /clearInterval/);
assert.match(source, /CloudRevisionConflictError/);
assert.match(source, /decideInitialCloudSync/);
assert.match(source, /hasLocalProgress/);
assert.doesNotMatch(source, /hasLocalGameSave\(window\.localStorage\)/);

console.log('cloud account coordinator lifecycle contract ok');
