import assert from 'node:assert/strict';
import { createInitialSaveState, normalizeLoadedSaveState } from '../save/gameSave';
import { applyTeamBuild, captureTeamBuild, normalizeTeamBuilds, previewTeamBuild, renameTeamBuild } from './teamBuilds';
import { fingerprintCloudBundle, isCloudSaveBundle } from '../cloud/cloudSaveModel';

const state = createInitialSaveState();
state.unlockedCharacterIds.push('aurelia');
state.partyIds = ['aurelia', 'marina'];
state.characterEquippedWeapon.aurelia = 'start_w_1';
state.inventoryArtifacts = [{ id: 'helm', name: 'Test Helmet', slot: 'helmet', set: 'Guardian', rarity: 4, equippedTo: 'aurelia' }];
state.characterEquippedArtifacts = { aurelia: { helmet: 'helm' } };
const build = captureTeamBuild(state, '  Boss Team  ', 'build-1');
assert.equal(build.name, 'Boss Team');
state.savedTeamBuilds = [build];
const renamed = renameTeamBuild(state, build.id, 'Campaign');
assert.equal(renamed.savedTeamBuilds![0].name, 'Campaign');
assert.deepEqual(renamed.savedTeamBuilds![0].members, build.members);
assert.equal(state.savedTeamBuilds[0].name, 'Boss Team');
assert.throws(() => renameTeamBuild(state, build.id, '   '));
assert.equal(normalizeLoadedSaveState(JSON.parse(JSON.stringify(renamed))).savedTeamBuilds![0].name, 'Campaign');
assert.deepEqual(normalizeLoadedSaveState({}).savedTeamBuilds, []);
assert.deepEqual(normalizeTeamBuilds([null, {}, { ...build, members: 'invalid' }]), []);
assert.equal(normalizeTeamBuilds(Array.from({ length: 7 }, (_, i) => ({ ...build, id: `build-${i}` }))).length, 5);
const cloudBundle = { saveState: state, pullHistory: [] };
const roundTrip = JSON.parse(JSON.stringify(cloudBundle));
assert.ok(isCloudSaveBundle(roundTrip));
assert.deepEqual(normalizeLoadedSaveState(roundTrip.saveState).savedTeamBuilds, [build]);
assert.notEqual(fingerprintCloudBundle(cloudBundle), fingerprintCloudBundle({ ...cloudBundle, saveState: renamed }), 'Renaming must trigger cloud autosave');

const changed = structuredClone(state);
changed.partyIds = ['marina'];
changed.characterEquippedWeapon = { kaelen: 'start_w_1', marina: 'start_w_3' };
changed.characterEquippedArtifacts = { kaelen: { helmet: 'helm' }, aurelia: {} };
changed.inventoryArtifacts![0].equippedTo = 'kaelen';
const before = structuredClone(changed);
const preview = previewTeamBuild(changed, build);
assert.equal(preview.issues.length, 0);
assert.ok(preview.transfers.length >= 2);
assert.deepEqual(changed, before, 'Preview must never change equipment');
const applied = applyTeamBuild(changed, build, true);
assert.deepEqual(applied.partyIds, ['aurelia', 'marina']);
assert.equal(applied.characterEquippedWeapon.aurelia, 'start_w_1');
assert.equal(applied.characterEquippedWeapon.kaelen, undefined);
assert.equal(applied.characterEquippedArtifacts!.kaelen.helmet, undefined);
assert.equal(applied.inventoryArtifacts![0].equippedTo, 'aurelia');
assert.equal(applied.mora, changed.mora);
assert.deepEqual(applied.characterHp, changed.characterHp);
assert.equal(applyTeamBuild(changed, build, false), changed, 'Combat must reject build application');

const missing = structuredClone(changed);
missing.inventoryArtifacts = [];
assert.ok(previewTeamBuild(missing, build).issues.some(i => i.includes('Test Helmet')));
assert.equal(applyTeamBuild(missing, build, true), missing, 'Missing gear must block the entire apply');
const locked = { ...changed, unlockedCharacterIds: ['marina'] };
assert.ok(previewTeamBuild(locked, build).issues.length);
assert.equal(applyTeamBuild(locked, build, true), locked);
const duplicate = structuredClone(build);
duplicate.members[1].weapon = duplicate.members[0].weapon;
assert.ok(previewTeamBuild(changed, duplicate).issues.length);
const noGear = structuredClone(build);
noGear.members[0].weapon = null;
noGear.members[0].artifacts = {};
const stripped = applyTeamBuild(state, noGear, true);
assert.equal(stripped.characterEquippedWeapon.aurelia, undefined);
assert.deepEqual(stripped.characterEquippedArtifacts!.aurelia, {});
assert.equal(stripped.inventoryArtifacts![0].equippedTo, undefined);
assert.equal(previewTeamBuild({ ...state, unlockedDamageSkins: ['Default'] }, { ...build, damageSkin: 'Void' }).issues.length, 1);
console.log('Saved team builds: rename, migration, preview, ownership, missing gear, combat guard and atomic apply passed');
