import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const layer = readFileSync(new URL('./components/RewardRevealLayer.tsx', import.meta.url), 'utf8');
const app = readFileSync(new URL('./App.tsx', import.meta.url), 'utf8');
const questSource = readFileSync(new URL('./components/SquadronQuestLedger.tsx', import.meta.url), 'utf8');
const loginSource = readFileSync(new URL('./components/LoginRewardModal.tsx', import.meta.url), 'utf8');
const shopSource = readFileSync(new URL('./components/GemsShop.tsx', import.meta.url), 'utf8');
const gachaSource = readFileSync(new URL('./components/GachaSimulator.tsx', import.meta.url), 'utf8');
const css = readFileSync(new URL('./index.css', import.meta.url), 'utf8');

const sourceSection = (source: string, start: string, end: string) => {
  const startIndex = source.indexOf(start);
  const endIndex = source.indexOf(end, startIndex + start.length);
  assert.ok(startIndex >= 0 && endIndex > startIndex, `missing source section: ${start}`);
  return source.slice(startIndex, endIndex);
};

const singleQuestHandler = sourceSection(app, 'const claimQuestReward', '// Claim all completed quests');
const claimAllHandler = sourceSection(app, 'const claimAllQuestRewards', 'const handleClaimLoginReward');
const loginHandler = sourceSection(app, 'const handleClaimLoginReward', 'const completeStartSimulation');
const shopUpdater = sourceSection(shopSource.replace(/\r\n/g, '\n'), 'onUpdateSaveState(prev =>', '  };\n\n  return (');

assert.match(layer, /createPortal/);
assert.match(layer, /pointer-events-none/);
assert.match(layer, /data-reward-reveal/);
assert.match(layer, /onAnimationComplete/);
assert.match(layer, /lowGraphics/);
assert.match(layer, /INVENTORY_FALLBACK_SELECTOR/);
assert.match(layer, /getBoundingClientRect/);
assert.match(layer, /setTimeout/);
assert.match(layer, /clearTimeout/);
assert.match(layer, /reducedMotion/);
assert.match(layer, /left: reducedMotion \? reveal\.destination\.x : reveal\.source\.x/);
assert.match(layer, /top: reducedMotion \? reveal\.destination\.y : reveal\.source\.y/);
assert.match(layer, /createRewardPulseController/);
assert.match(layer, /pulseController\.current\?\.reset\(\)/);

assert.match(app, /data-reward-target="mora"/);
assert.match(app, /data-reward-target="gems"/);
assert.match(app, /data-reward-target="forge"/);
assert.match(app, /data-reward-target="forge"[\s\S]{0,800}id="dash_screen_inventory"/);
assert.doesNotMatch(app, /data-reward-target="forge"[\s\S]{0,800}id="dash_screen_home"/);
assert.match(app, /data-reward-target="inventory-fallback"/);
assert.match(app, /<RewardRevealLayer/);
assert.equal(app.match(/<RewardRevealLayer/g)?.length, 1);
assert.match(app, /appendRewardEvents/);
assert.match(app, /normalizeRewardEvents/);
assert.match(app, /const enqueueRewardReveal = useCallback/);
assert.match(app, /setRewardRevealQueue\(current => current\.filter\(event => event\.id !== id\)\)/);
assert.match(app, /pendingRewardTransactionsRef/);
assert.match(app, /rewardTransactionLocksRef/);
assert.match(app, /transaction\.status = 'accepted'/);
assert.match(app, /transaction\.status = 'rejected'/);
assert.match(app, /flushAcceptedRewardTransactions/);
assert.match(app, /useEffect\(\(\) => \{[\s\S]*?flushAcceptedRewardTransactions\(saveState\)/);
assert.match(app, /prev\.activeQuests\.find\(quest =>[\s\S]*?quest\.id === questId[\s\S]*?quest\.completed/);
assert.match(app, /prev\.activeQuests\.filter\(quest => quest\.completed\)/);
assert.match(app, /completedQuestCountBefore: prev\.completedQuestIds\.length/);
assert.doesNotMatch(singleQuestHandler, /!prev\.completedQuestIds\.includes/);
assert.doesNotMatch(claimAllHandler, /!prev\.completedQuestIds\.includes/);
assert.doesNotMatch(app, /enqueueRewardReveal\(loginRewardEvents/);
assert.doesNotMatch(singleQuestHandler, /saveState\./);
assert.doesNotMatch(claimAllHandler, /saveState\./);
assert.doesNotMatch(singleQuestHandler, /enqueueRewardReveal|showInGameAlert|AetheriaAudioEngine/);
assert.doesNotMatch(claimAllHandler, /enqueueRewardReveal|showInGameAlert|AetheriaAudioEngine/);
assert.match(loginHandler, /currentClaimed\.includes\(day\)/);
assert.match(loginHandler, /day !== currentClaimed\.length \+ 1/);
assert.match(loginHandler, /day > \(prev\.unlockedDaysCount \|\| 1\)/);
assert.match(loginHandler, /transaction\.commit = \{ type: 'login', day \}/);
assert.doesNotMatch(loginHandler, /enqueueRewardReveal|showInGameAlert|AetheriaAudioEngine/);
assert.match(app, /gemsDiff > 0/);
assert.match(app, /moraDiff > 0/);
assert.match(app, /story-\$\{stageId\}/);
assert.match(app, /data-reward-source=\{`story-\$\{storyBattleConfig\.stageId\}`\}/);
assert.match(app, /quest-\$\{quest\.id\}/);
assert.match(app, /quest-claim-all/);
assert.match(app, /login-\$\{day\}/);
assert.match(app, /onRewardReveal=\{enqueueRewardReveal\}/);
assert.match(app, /deferredRewardRevealsRef/);
assert.match(app, /deferRewardReveal\(\[createRewardRevealEvent\('weapon', 1\)\], 'summon-results'\)/);
assert.match(app, /onRewardSourceReady=\{flushDeferredRewardReveals\}/);

assert.match(questSource, /data-reward-source=\{`quest-\$\{q\.id\}`\}/);
assert.match(questSource, /data-reward-source="quest-claim-all"/);
assert.match(loginSource, /data-reward-source=\{`login-\$\{day\}`\}/);
assert.match(shopSource, /onRewardReveal\?/);
assert.match(shopSource, /purchasedShopItemIds[\s\S]*?includes\(item\.id\)\) return/);
assert.match(shopSource, /pendingPurchasesRef/);
assert.match(shopSource, /inventoryArtifacts[\s\S]*?some\(artifact => artifact\.id === pending\.artifactId\)/);
assert.match(shopSource, /useEffect\(\(\) => \{[\s\S]*?onRewardReveal\?\./);
assert.match(shopUpdater, /purchased\.includes\(item\.id\)\) return prev/);
assert.match(shopUpdater, /prev\.aetherGems < item\.price/);
assert.doesNotMatch(shopUpdater, /onRewardReveal|onShowAlert/);
assert.match(shopSource, /data-reward-source=\{`shop-\$\{item\.id\}`\}/);
assert.match(gachaSource, /data-reward-source="summon-results"/);
assert.match(gachaSource, /animationPhase === 'showcase'[\s\S]{0,500}data-reward-source="summon-results"/);
assert.match(gachaSource, /onRewardSourceReady\?/);
assert.match(gachaSource, /animationPhase !== 'showcase'[\s\S]*?onRewardSourceReady\?\.\('summon-results'\)/);
assert.doesNotMatch(gachaSource, /onRewardReveal/);

assert.match(css, /\[data-reward-pulse="true"\]/);
assert.match(css, /reward-target-pulse 260ms/);
assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*?reward-target-outline 260ms/);

console.log('reward reveal integration contracts ok');
